site_name: mps-gotchas

# Meta tags (placed in header)
site_description: This website describes gotchas when working with MPS and gives some hints on how to write clean code in MPS.
site_author: Alexander Pann
site_url: https://alexanderpann.github.io/mps-gotchas

# Repository (add link to repository on each page)
repo_name: mps-gotchas
repo_url: http://github.com/alexanderpann/mps-gotchas
edit_uri: edit/main/src/doc/docs/

# Copyright (shown at the footer)
copyright: 'Copyright &copy; 2021 Alexander Pann'

# Material theme
theme:
  name: 'material'
  features:
    - navigation.top
    - navigation.instant
    - header.autohide
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

#plugins:
#  - search
#    Required for variables support (https://github.com/rosscdh/mkdocs-markdownextradata-plugin)
#  - markdownextradata
plugins:
  - search
  - git-revision-date-localized

#extra:
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'

#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/you
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/you

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
nav:
  - Home: index.md
  - General: gotchas/general/index.md
  - Aspects:
    - Structure: gotchas/aspects/structure/index.md
    - Editor: gotchas/aspects/editor/index.md
    - Constraints: gotchas/aspects/constraints/index.md
    - Behaviour: gotchas/aspects/behavior/index.md
    - Actions: gotchas/aspects/actions/index.md
    - Typesystem: gotchas/aspects/typesystem/index.md
    - Intentions: gotchas/aspects/intentions/index.md
    - Migrations: gotchas/aspects/migrations/index.md
    - Generator: gotchas/aspects/generator/index.md
    - Plugin: gotchas/aspects/plugin/index.md
    - TextGen: gotchas/aspects/textGen/index.md
    - Tests: gotchas/aspects/tests/index.md
    - Dataflow: gotchas/aspects/dataFlow/index.md
    - Feedback: gotchas/aspects/feedback/index.md
    - Refactorings: gotchas/aspects/refactorings/index.md
    - Find Usages: gotchas/aspects/findUsages/index.md
    - VCS: gotchas/aspects/vcs/index.md
    - Scripts: gotchas/aspects/scripts/index.md
    - Listener*: gotchas/aspects/listener/index.md
    - Documentation*: gotchas/aspects/documentation/index.md
    - Polyfun*: gotchas/aspects/polyfun/index.md
    - Virtual Interfaces*: gotchas/aspects/virtualinterfaces/index.md
    - Transformations*: gotchas/aspects/transformations/index.md
  - Languages:
      - Base Language: gotchas/languages/baselanguage.md
      - Collections Language: gotchas/languages/baselanguage_collections.md
      - MPS Extensions: gotchas/languages/mps_extensions.md
      - Mbeddr: gotchas/languages/mbeddr_mpsutil.md
      - Misc: gotchas/languages/index.md
  - Console: gotchas/console/index.md
  - Plugins: gotchas/plugins/index.md
  - Build: gotchas/build/index.md
  - External Files and Tools: gotchas/external_files_and_tools/index.md
  - Internal MPS: gotchas/mps_internal/index.md
  - Miscellaneous: gotchas/misc/index.md
  - General programming principles: clean_code/programming_principles.md
  - Deprecation: clean_code/deprecation.md
  - Clean code (MPS):
    - General: clean_code/mps/general.md
    - Miscellaneous: clean_code/mps/misc.md
  - Clean code (Base Language):
    - Java Style Guide: clean_code/baselanguage/java_style_guide.md
    - General: clean_code/baselanguage/general.md
  - Reference:
    - Icons: reference/icons.md
    - Exceptions: reference/exceptions.md