name: Build documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          SSHKEY: ${{ secrets.SSH_KEY_PRIVATE }} # ----- BEGIN RSA PRIVATE KEY----- ...
      - run: ssh -T git@github.com || true

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Build with Gradle
        run: ./gradlew mkdocsPublish